export { default as Navbar } from './Navbar/Navbar'
export { default as Home } from './Home/Home'
export { default as Detail } from './Home/Category/Detail'
export { default as About } from './About/About'
export { default as Course_map } from './Course_map/Course_map'